import os
import glob
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler
from sklearn.pipeline import make_pipeline
import joblib

FEATURES_DIR = "data/lake/features"
MODEL_DIR = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "anomaly_detector.joblib")

def main():
    # 1. Read the parquet files generated by your feature stream script
    file_pattern = os.path.join(FEATURES_DIR, "**", "*.parquet")
    parquet_files = glob.glob(file_pattern, recursive=True)
    
    if not parquet_files:
        print(f"Error: No parquet files found in {FEATURES_DIR}.")
        print("Please run ml_feature_stream.py after your test injection script first.")
        return

    df = pd.concat([pd.read_parquet(f) for f in parquet_files], ignore_index=True)
    df = df.drop_duplicates(subset=["page_title"]).dropna()
    print(f"Loaded {len(df)} pages from your local feature lake.")

    # 2. Extract our engineered features
    feature_cols = [
        "edit_count", "unique_editors", "total_byte_changes", 
        "bot_ratio", "minor_edit_ratio", "relative_growth", 
        "human_bot_friction", "editor_concentration"
    ]
    X = df[feature_cols]

    # 3. Build the 1% model pipeline
    pipeline = make_pipeline(
        RobustScaler(),
        IsolationForest(contamination=0.01, random_state=42, n_jobs=-1)
    )

    # 4. Fit the model on your test data
    print("Training Isolation Forest detector...")
    pipeline.fit(X)

    # 5. Predict to see if it flags your spike page
    predictions = pipeline.predict(X)
    df["anomaly_score"] = pipeline.decision_function(X)
    df["is_anomaly"] = (predictions == -1).astype(int)

    # 6. Print out exactly what the model decided
    print("\n=== LOCAL DETECTION TEST RESULTS ===")
    print(df[["page_title", "edit_count", "total_byte_changes", "is_anomaly", "anomaly_score"]].to_string(index=False))

    # 7. Save the trained brain
    os.makedirs(MODEL_DIR, exist_ok=True)
    joblib.dump(pipeline, MODEL_PATH)
    print(f"\n💾 Model pipeline successfully saved to: {MODEL_PATH}")

if __name__ == "__main__":
    main()
