import os
import sys
import json

# Ensure Spark's Python workers use this same interpreter (with numpy/pyspark installed)
# instead of falling back to the bare system python3 on PATH.
os.environ.setdefault("PYSPARK_PYTHON", sys.executable)
os.environ.setdefault("PYSPARK_DRIVER_PYTHON", sys.executable)

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, udf
from pyspark.sql.types import DoubleType
from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler, RobustScaler
from pyspark.ml.clustering import KMeans
from pyspark.ml.linalg import Vectors

FEATURES_DIR = os.environ.get("FEATURES_DIR", "data/lake/features")
MODEL_DIR = os.environ.get("MODEL_DIR", "models")
MODEL_PATH = os.path.join(MODEL_DIR, "anomaly_detector_spark")
THRESHOLD_PATH = os.path.join(MODEL_DIR, "anomaly_detector_spark_threshold.json")

FEATURE_COLS = [
    "edit_count", "unique_editors", "total_byte_changes",
    "bot_ratio", "minor_edit_ratio", "relative_growth",
    "human_bot_friction", "editor_concentration"
]

# Fraction of rows treated as anomalous when picking the distance threshold.
CONTAMINATION = 0.01

# Spark's KMeans requires k >= 2 (unlike sklearn, k=1 is rejected). Keep it small anyway:
# scoring below always measures distance to the MAJORITY cluster's centroid, never to a
# point's own assigned cluster, specifically so a tight group of outliers can't carve out
# its own minority cluster and hide behind a small self-distance.
K_CLUSTERS = 2


def main():
    spark = (
        SparkSession.builder
        .appName("WikiPulseAnomalyTrainerSpark")
        .master("local[2]")
        .config("spark.driver.memory", "1g")
        .config("spark.sql.shuffle.partitions", "4")
        .config("spark.ui.enabled", "false")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("WARN")

    # 1. Read the parquet files generated by your feature stream script
    if not os.path.isdir(FEATURES_DIR):
        print(f"❌ Error: No parquet files found in {FEATURES_DIR}.")
        print("Please run ml_feature_stream.py after your test injection script first.")
        spark.stop()
        return

    df = (
        spark.read.parquet(FEATURES_DIR)
        .dropDuplicates(["page_title"])
        .na.drop()
    )
    row_count = df.count()
    if row_count == 0:
        print(f"❌ Error: No parquet files found in {FEATURES_DIR}.")
        print("Please run ml_feature_stream.py after your test injection script first.")
        spark.stop()
        return
    print(f"📋 Loaded {row_count} pages from your local feature lake.")

    # 2. Build the spark.ml pipeline: assemble -> scale -> cluster
    assembler = VectorAssembler(inputCols=FEATURE_COLS, outputCol="raw_features")
    scaler = RobustScaler(inputCol="raw_features", outputCol="scaled_features")
    kmeans = KMeans(featuresCol="scaled_features", predictionCol="cluster", k=K_CLUSTERS, seed=42)
    pipeline = Pipeline(stages=[assembler, scaler, kmeans])

    # 3. Fit the model on your test data
    print("🧠 Training KMeans anomaly detector...")
    model = pipeline.fit(df)

    # 4. Identify the majority ("normal") cluster and score every row by distance to
    # ITS centroid specifically -- not to whichever cluster each row was assigned to.
    # Distance-to-own-cluster is meaningless for outlier detection: a point assigned to
    # a cluster is by definition close to that cluster's center, so a small tight group
    # of anomalies would just form its own minority cluster and score a self-distance
    # near zero, hiding completely. Anchoring on the majority cluster's centroid avoids
    # that failure mode entirely.
    transformed = model.transform(df)
    kmeans_model = model.stages[-1]
    normal_cluster_id = (
        transformed.groupBy("cluster").count()
        .orderBy(col("count").desc())
        .first()["cluster"]
    )
    normal_center = Vectors.dense(kmeans_model.clusterCenters()[normal_cluster_id])

    def distance_to_normal(features):
        return float(features.squared_distance(normal_center) ** 0.5)

    distance_udf = udf(distance_to_normal, DoubleType())

    scored = transformed.withColumn("anomaly_score", distance_udf(col("scaled_features")))

    # 5. Threshold: top CONTAMINATION fraction of distances counts as anomalous
    threshold = scored.approxQuantile("anomaly_score", [1.0 - CONTAMINATION], 0.01)[0]
    scored = scored.withColumn("is_anomaly", (col("anomaly_score") >= threshold).cast("int"))

    # 6. Print out exactly what the model decided
    print("\n=== LOCAL DETECTION TEST RESULTS ===")
    scored.select(
        "page_title", "edit_count", "total_byte_changes", "is_anomaly", "anomaly_score"
    ).orderBy(col("anomaly_score").desc()).show(truncate=False)

    # 7. Save the trained pipeline and the threshold it was calibrated against
    os.makedirs(MODEL_DIR, exist_ok=True)
    model.write().overwrite().save(MODEL_PATH)
    with open(THRESHOLD_PATH, "w") as f:
        json.dump({
            "threshold": threshold,
            "normal_center": list(normal_center),
            "k": K_CLUSTERS,
            "contamination": CONTAMINATION,
        }, f)
    print(f"\n💾 Model pipeline successfully saved to: {MODEL_PATH}")
    print(f"💾 Anomaly threshold ({threshold:.4f}) saved to: {THRESHOLD_PATH}")

    spark.stop()


if __name__ == "__main__":
    main()
